/**
 * DataElement enum for ISO 8583
 * Contains all non-reserved fields up to 104 + private use fields (120-127)
 */
export enum DataElement {
  // Primary fields (1-64)
  PRIMARY_ACCOUNT_NUMBER              = 2,
  PROCESSING_CODE                     = 3,
  TRANSACTION_AMOUNT                  = 4,
  SETTLEMENT_AMOUNT                   = 5,
  CARDHOLDER_BILLING_AMOUNT           = 6,
  TRANSMISSION_DATE_TIME              = 7,
  CONVERSION_RATE_CARDHOLDER_BILLING  = 9,
  SYSTEM_TRACE_AUDIT_NUMBER           = 11,
  LOCAL_TRANSACTION_TIME              = 12,
  LOCAL_TRANSACTION_DATE              = 13,
  EXPIRATION_DATE                     = 14,
  SETTLEMENT_DATE                     = 15,
  CONVERSION_DATE                     = 16,
  DATE_CAPTURE                        = 17,
  MERCHANT_TYPE                       = 18,
  ACQUIRING_INSTITUTION_COUNTRY_CODE  = 19,
  POINT_OF_SERVICE_ENTRY_MODE         = 22,
  CARD_SEQUENCE_NUMBER                = 23,
  POINT_OF_SERVICE_CONDITION_CODE     = 25,
  ACQUIRING_INSTITUTION_ID            = 32,
  FORWARDING_INSTITUTION_ID           = 33,
  TRACK_2_DATA                        = 35,
  RETRIEVAL_REFERENCE_NUMBER          = 37,
  AUTHORIZATION_ID_RESPONSE           = 38,
  RESPONSE_CODE                       = 39,
  SERVICE_RESTRICTION_CODE            = 40,
  CARD_ACCEPTOR_TERMINAL_ID           = 41,
  CARD_ACCEPTOR_ID_CODE               = 42,
  CARD_ACCEPTOR_NAME_LOCATION         = 43,
  ADDITIONAL_RESPONSE_DATA            = 44,
  TRACK_1_DATA                        = 45,
  ADDITIONAL_DATA_ISO                 = 46,
  ADDITIONAL_DATA_NATIONAL            = 47,
  ADDITIONAL_DATA_PRIVATE             = 48,
  TRANSACTION_CURRENCY_CODE           = 49,
  SETTLEMENT_CURRENCY_CODE            = 50,
  CARDHOLDER_BILLING_CURRENCY_CODE    = 51,
  PIN_DATA                            = 52,
  SECURITY_RELATED_CONTROL_INFORMATION = 53,
  ADDITIONAL_AMOUNTS                  = 54,
  ICC_CARD_SYSTEM_RELATED_DATA        = 55,
  MESSAGE_REASON_CODE                 = 56,
  AUTHORIZATION_LIFE_CYCLE            = 57,
  AUTHORISER                          = 58,
  TRANSPORT_DATA                      = 59,

  // MAC field
  MESSAGE_AUTHENTICATION_CODE_64      = 64,

  // Fields 66 to 104 (non-reserved, commonly used)
  SETTLEMENT_CODE                     = 66,
  NETWORK_MANAGEMENT_INFO_CODE        = 70,
  ACTION_DATE                         = 73,
  NUMBER_OF_CREDITS                   = 74,
  CREDITS_REVERSAL_NUMBER             = 75,
  NUMBER_OF_DEBITS                    = 76,
  DEBITS_REVERSAL_NUMBER              = 77,
  TRANSFER_NUMBER                     = 78,
  TRANSFER_REVERSAL_NUMBER            = 79,
  INQUIRIES_NUMBER                    = 80,
  AUTHORIZATIONS_NUMBER               = 81,
  CREDITS_PROCESSING_FEE_AMOUNT       = 82,
  DEBITS_PROCESSING_FEE_AMOUNT        = 83,
  CREDITS_TRANSACTION_FEE_AMOUNT      = 84,
  DEBITS_TRANSACTION_FEE_AMOUNT       = 85,
  CREDITS_AMOUNT                      = 86,
  DEBITS_AMOUNT                       = 87,
  CREDITS_REVERSAL_AMOUNT             = 88,
  DEBITS_REVERSAL_AMOUNT              = 89,
  ORIGINAL_DATA_ELEMENTS              = 90,
  FILE_UPDATE_CODE                    = 91,
  FILE_SECURITY_CODE                  = 92,
  RESPONSE_INDICATOR                  = 93,
  SERVICE_INDICATOR                   = 94,
  REPLACEMENT_AMOUNTS                 = 95,
  KEY_MANAGEMENT_DATA                 = 96,
  AMOUNT_NET_SETTLEMENT               = 97,
  PAYEE                               = 98,
  SETTLEMENT_INSTITUTION_ID           = 99,
  RECEIVING_INSTITUTION_ID            = 100,
  FILE_NAME                           = 101,
  ACCOUNT_ID_1                        = 102,
  ACCOUNT_ID_2                        = 103,
  TRANSACTION_DESCRIPTION             = 104,

  // Private Use Fields (120 - 127)
  PRIVATE_USE_120                     = 120,
  PRIVATE_USE_121                     = 121,
  PRIVATE_USE_122                     = 122,
  PRIVATE_USE_123                     = 123,
  PRIVATE_USE_124                     = 124,
  PRIVATE_USE_125                     = 125,
  PRIVATE_USE_126                     = 126,
  PRIVATE_USE_127                     = 127,

  // Secondary MAC (when secondary bitmap is used)
  MESSAGE_AUTHENTICATION_CODE_128     = 128
}
